# Начало работы с tensorflow

## Полезные ссылки:
1. [Intriduction to Tensors](https://www.tensorflow.org/guide/tensor)
2. [Тензоры tf.constant и tf.Variable. Индексирование и изменение формы](https://proproprogs.ru/tensorflow/tf-tenzory-tfconstant-i-tfvariable-indeksirovanie-i-izmenenie-formy)
3. [Tensorflow 2 уроки](https://www.youtube.com/watch?v=mSDPZsyIP6Y&list=PLA0M1Bcd0w8ynD1umfubKq1OBYRXhXkmH&index=3)


In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [2]:
import tensorflow as tf
import numpy as np

Во второй версии tensorflow сразу включено активное выполнение (executing_eagerly)

In [3]:
tf.executing_eagerly()

True

## Как создать тензор?

### Использовать метод tf.constant, который создает неизменяемые тензоры

tf.constant(value, dtype=None, shape=None, name="Const")
- value - значение тензора
- dtype - тип данных тензора
- shape - размерность тензора
- name - имя тензора

In [4]:
# Задаем тензор в виде скаляра:
a = tf.constant(1)
print(a)

tf.Tensor(1, shape=(), dtype=int32)


Результат: а - это тензор, со значением 1, не имеющий размерности (осей), с типом int32

In [5]:
# Зададим тензок в виде матрицы 1 х 1:
a = tf.constant(1, shape=(1, 1))
print(a)

tf.Tensor([[1]], shape=(1, 1), dtype=int32)


Результат: полученный тензок имеет две оси (его ранг равен 2)

In [6]:
a1 = tf.constant(1, shape=(2, 2, 3))
print(a1)

tf.Tensor(
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]], shape=(2, 2, 3), dtype=int32)


In [7]:
# Зададим тензок как вектор:
b = tf.constant([1, 2, 3, 4])
print(b)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


Результат: у полученного тензора одна ось (его ранг равен 1)

In [8]:
# Зададим тип данных нового тензора при его создании:
c = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]], dtype=tf.float16)
print(c)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


- Тензор должен включать **только данные одного типа**!
- Тензоры создаются на основе прямоугольных таблиц чисел (количество элементов в каждой строке должно быть одинаковым)

### Для создания изменяемых тензоров используется класс tf.Variable()

In [9]:
# Создаем тензор на основе скаляра:
v1 = tf.Variable(-1.2)
print(v1)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=-1.2>


In [10]:
# Создаем тензор на основе списка
v2 = tf.Variable([4, 5, 6, 7], dtype=tf.float32)
print(v2)

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([4., 5., 6., 7.], dtype=float32)>


In [11]:
# Создаем тензор на основе уже существующего тензора:
v3 = tf.Variable(b)
print(v3)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>


## Как изменить тип данных в уже созданном тензоре?

In [12]:
# Изменим тип данных уже созданного тензора:
b2 = tf.cast(a, dtype=tf.float32)
print(b2)

tf.Tensor([[1.]], shape=(1, 1), dtype=float32)


## Как преобразовать тензор в массив numpy?

Для этого можно использовать несколько вариантов:

In [13]:
c2 = np.array(c)
c2

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [14]:
c3 = c.numpy()
c3

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

## Как изменить значения в изменяемых тензорах?

### Меняем все значения

In [15]:
print(f"before: {v2}")
# меняем значение:
v2.assign([4, 3, 2, 1])
print(f"after: {v2}")

before: <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([4., 5., 6., 7.], dtype=float32)>
after: <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([4., 3., 2., 1.], dtype=float32)>


Размерности передаваемых в метод **.assign** данных должны совпадать с размерностью тензора!

### Прибавляем значения к уже существующим

In [16]:
v2.assign_add([2, 2, 2, 2])
v2

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([6., 5., 4., 3.], dtype=float32)>

### Вычитаем значения из уже существующих

In [17]:
v2.assign_sub([4, 4, 4, 4])
v2

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([ 2.,  1.,  0., -1.], dtype=float32)>

## Как создать копую существующего тензора?

In [18]:
v4 = tf.Variable(v2)
v4

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([ 2.,  1.,  0., -1.], dtype=float32)>

In [19]:
id(v2)

140217361955008

In [20]:
id(v4)

140217330884464

Эти ссылки (v2 и v4) указывают на разные объекты!

## Индексирование

### Получение срезов

In [21]:
c

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [22]:
s1 = c[0]
s1

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 2.], dtype=float16)>

In [23]:
s2 = c[:2]
s2

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

In [24]:
s3 = c[-1]
s3

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([5., 6.], dtype=float16)>

In [25]:
s4 = c[(2, 1)]
s4

<tf.Tensor: shape=(), dtype=float16, numpy=6.0>

In [26]:
s5 = c[1, :1]
s5

<tf.Tensor: shape=(1,), dtype=float16, numpy=array([3.], dtype=float16)>

- Срезы ссылаются на базовый тензор. Копирование данных не происходит.
- Если изменить значения в срезе, то изменится базовый тензор.
- При этом, само значения тензора-среза не изменится, т.к. он представляется как незменный тензор

In [27]:
s6 = v4[:-1]

In [28]:
s6.assign([10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=float32, numpy=array([10., 10., 10., -1.], dtype=float32)>

In [29]:
v4

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([10., 10., 10., -1.], dtype=float32)>

In [30]:
s6

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 1., 0.], dtype=float32)>

### Списочное индексирование

In [31]:
x = tf.constant(range(10)) + 5
# на основе индексов 0 и 4 создаем новый тензор:
x_indx = tf.gather(x, [0, 4])

In [32]:
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14], dtype=int32)>

In [33]:
x_indx

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 9], dtype=int32)>

In [34]:
x2 = tf.constant([[1, 2, 7], [3, 4, 8], [5, 6, 9]])
x2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]], dtype=int32)>

In [35]:
val_indx = x2[(1, 2)]
val_indx

<tf.Tensor: shape=(), dtype=int32, numpy=8>

## Как изменить форму вектора (число элементов по осям)?

In [36]:
# создадим одномерный тензор:
a = tf.constant(range(30))
a

<tf.Tensor: shape=(30,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int32)>

In [37]:
# превратим этот тензор из одномерного в двумерный:
b = tf.reshape(a, [5, 6])
b

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]], dtype=int32)>

- Функция **tf.reshape()** не создает новую матрицу, а меняет только форму
- Не меняет порядок следования элементов
- Работает очень быстро
- Ее можно применять для тензоров большого размера

In [44]:
# по одной из осей можно не указывать размерность, и она будет вычислена автоматически
d = tf.reshape(a, [5, -1])
d

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]], dtype=int32)>

## Операция транспонирования

In [45]:
b_T = tf.transpose(b, perm=[1,0])

In [46]:
b_T

<tf.Tensor: shape=(6, 5), dtype=int32, numpy=
array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]], dtype=int32)>