# Математические операции и функции над тензорами

## Полезные ссылки:
1. [Математические операции и функции над тензорами](https://proproprogs.ru/tensorflow/tf-matematicheskie-operacii-i-funkcii-nad-tenzorami)
2. [Tensorflow 2 уроки](https://www.youtube.com/watch?v=AzT8-K_Cvyk&list=PLA0M1Bcd0w8ynD1umfubKq1OBYRXhXkmH&index=3)

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [2]:
import tensorflow as tf
import numpy as np

## Функции автозаполнения

### Создаем тензоры, состоящие из всех нулей

In [3]:
a = tf.zeros((3, 3))
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Создаем тензоры из всех единиц

In [4]:
b = tf.ones((5, 3))
b

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

### Создаем нулевые и единичные тензоры на основе других тензоров

Создадим тензор, состоящий из нулей, на основе терзора **b**:

In [7]:
d = tf.zeros_like(b)
d

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

Создадим тензор из всех единиц на основе тензора **a**:

In [6]:
c = tf.ones_like(a)
c

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

### Создаем тензор, состоящий из единиц, распложенных по главной диагонали

In [8]:
e = tf.eye(3)
e

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

Не обязательно создавать квадратные матрицы:

In [10]:
e = tf.eye(3, 2)
e

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 0.]], dtype=float32)>

### Создаем тензоры с заданной размерностью и заданными значениями

In [13]:
g = tf.fill((2, 3), -2)
g

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-2, -2, -2],
       [-2, -2, -2]], dtype=int32)>

### Создаем копии тензоров с сохранение всех их значений

In [11]:
f = tf.identity(c)
f

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [12]:
print(id(c), id(f), sep='\n')

139634042144720
139633953638928


### Создаем одномерные списки в заданных интервалах

In [14]:
h = tf.range(1, 11, 0.5)
h

<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5],
      dtype=float32)>

## Генерация случайных значений

### tf.random.normal()

Возвращает тензор с нормально распределенными случайными величинами с заданным МО и СКО

In [15]:
a = tf.random.normal((2, 4), 0, 0.1)
a

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.11890186, -0.05191514, -0.02592726,  0.06438391],
       [ 0.04679037, -0.02248388,  0.00179708,  0.14450902]],
      dtype=float32)>

- сформирован тензор размером 2 х 4
- с нулевым математическим ожиданием (МО) = 0
- и среднеквадратическим отклонением (СКО) = 0,1

### tf.random.truncated_normal()

Возвоазает тензор нормальных СВ, но в диапазоне +\- 2-х сигм относительно МО.

In [19]:
c = tf.random.truncated_normal((2, 4), 0)
c

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.1422753 , -0.1546823 ,  0.2714279 ,  0.14501382],
       [-1.2395664 ,  0.8009103 , -0.44527927,  0.24069124]],
      dtype=float32)>

### tf.random.uniform()

Возвращает тензор с равномерным распределением в указанном интервале

In [16]:
b = tf.random.uniform((2, 2), -1, 1)
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.8560152 ,  0.18708992],
       [-0.71353936, -0.20316958]], dtype=float32)>

### tf.shuffle()

Перемешивает существующие значения тензора

In [36]:
b = tf.random.shuffle(c)
b

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-1.2395664 ,  0.8009103 , -0.44527927,  0.24069124],
       [-0.1422753 , -0.1546823 ,  0.2714279 ,  0.14501382]],
      dtype=float32)>

### tf.random.set_seed()

Устанавливает "зерно" для датчика случайных чисел

In [37]:
tf.random.set_seed(1)
d = tf.random.truncated_normal((1, 5), -1, 0.1)
d

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[-1.110122  , -0.84542483, -0.9616356 , -1.0879657 , -0.85944796]],
      dtype=float32)>

## Математические функции

Описанные в этом разделе функции выполняют математические операции с тензорами поэлементно

In [38]:
# создадим два тензора:
a = tf.constant([1, 2, 3])
b = tf.constant([9, 8, 7])

In [39]:
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [40]:
b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([9, 8, 7], dtype=int32)>

### Складываем тензоры между собой

In [41]:
tf.add(a, b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

**Условие**: При складывании тензоров, их размерности должны быть согласованными

In [42]:
a + b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

### Вычитание одного тензора из другого

In [43]:
tf.subtract(a, b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

In [44]:
a - b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

### Поэлементное деление одного тензора на другой

In [45]:
tf.divide(a, b)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [46]:
a / b

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [49]:
# целочисленное деление:
a // b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0], dtype=int32)>

### Поэлементное умножение одного тензора на другой

In [50]:
tf.multiply(a, b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

In [51]:
a * b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

### Поэлементное возведение тензора в степень

In [52]:
a ** 2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [53]:
a ** b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([   1,  256, 2187], dtype=int32)>

## Векторное умножение

### Внешнее векторное умножение

In [56]:
tf.tensordot(a, b, axes=0)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9,  8,  7],
       [18, 16, 14],
       [27, 24, 21]], dtype=int32)>

- Для векторов **axes** должно быть равно **0**
- На выходе получаем **матрицу**

### Внутреннее векторное умножение

In [58]:
tf.tensordot(a, b, axes=1)

<tf.Tensor: shape=(), dtype=int32, numpy=46>

- Для векторов **axes** должно быть равно **1**
- На выходе получаем **одно число**

## Матричное умножение

In [59]:
# создадим тензоры-матрицы:
a2 = tf.constant(tf.range(1, 10), shape=(3, 3))
b2 = tf.constant(tf.range(5, 14), shape=(3, 3))

In [62]:
a2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [63]:
b2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]], dtype=int32)>

In [61]:
tf.matmul(a2, b2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 54,  60,  66],
       [126, 141, 156],
       [198, 222, 246]], dtype=int32)>

In [64]:
a2 @ b2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 54,  60,  66],
       [126, 141, 156],
       [198, 222, 246]], dtype=int32)>

## Стандартные математические функции

In [65]:
# зададим матрицу m:
m = tf.tensordot(a, b, axes=0)
m

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9,  8,  7],
       [18, 16, 14],
       [27, 24, 21]], dtype=int32)>

### Сумма значений всех элементов матрицы **m**

In [66]:
tf.reduce_sum(m)

<tf.Tensor: shape=(), dtype=int32, numpy=144>

### Суммирование значений матрицы по столбцам

In [67]:
tf.reduce_sum(m, axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([54, 48, 42], dtype=int32)>

**axis=0** означает, что мы берем каждую строку матрицы и поочередно и суммируем между собой

### Суммпрование значений матрицы по строкам

In [68]:
tf.reduce_sum(m, axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([24, 48, 72], dtype=int32)>

>[!note]
> Если указать в виде словаря сразу несколько осей, то суммирование будет происходить по ним

In [69]:
tf.reduce_sum(m, axis=[0, 1])

<tf.Tensor: shape=(), dtype=int32, numpy=144>

В результате получилось суммирование всех значений матрицы

### Вычисление среднего арифметического значений тензора

In [72]:
m

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9,  8,  7],
       [18, 16, 14],
       [27, 24, 21]], dtype=int32)>

In [71]:
# среднее арифметическое всех значений матрицы:
tf.reduce_mean(m)

<tf.Tensor: shape=(), dtype=int32, numpy=16>

In [73]:
# среднее арифметическое по столбцам:
tf.reduce_mean(m, axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([18, 16, 14], dtype=int32)>

In [74]:
# среднее арифметическое по строкам:
tf.reduce_mean(m, axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 8, 16, 24], dtype=int32)>

### Вычисление максимального и минимального значений матрицы

In [77]:
m

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9,  8,  7],
       [18, 16, 14],
       [27, 24, 21]], dtype=int32)>

In [75]:
tf.reduce_max(m)

<tf.Tensor: shape=(), dtype=int32, numpy=27>

In [76]:
tf.reduce_min(m)

<tf.Tensor: shape=(), dtype=int32, numpy=7>

>[!note]
>Аналогичным образом все эти функции работают с разными осями

In [78]:
# максимум по столбцам
tf.reduce_max(m, axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([27, 24, 21], dtype=int32)>

In [79]:
# минимум по строкам
tf.reduce_min(m, axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 7, 14, 21], dtype=int32)>

### Вычисление произведения элементов матрицы

In [80]:
tf.reduce_prod(m)

<tf.Tensor: shape=(), dtype=int32, numpy=1883394048>

In [83]:
# по столбцам
tf.reduce_prod(m, axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4374, 3072, 2058], dtype=int32)>

In [84]:
# по строкам
tf.reduce_prod(m, axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  504,  4032, 13608], dtype=int32)>

### Вычисляем корень квадратный элементов тензора

In [86]:
m

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9,  8,  7],
       [18, 16, 14],
       [27, 24, 21]], dtype=int32)>

In [85]:
tf.sqrt(tf.cast(m, dtype=tf.float32))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[3.       , 2.828427 , 2.6457512],
       [4.2426405, 4.       , 3.7416575],
       [5.196152 , 4.8989797, 4.582576 ]], dtype=float32)>

**Условие**: значения тензора должны быть **вещественными**

### Возведение значений тензора в квадрат

In [87]:
tf.square(m)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 81,  64,  49],
       [324, 256, 196],
       [729, 576, 441]], dtype=int32)>

### Тригонометрические функции

In [90]:
k = tf.range(-3.14, 3.14, 1)
k

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([-3.14     , -2.14     , -1.1400001, -0.1400001,  0.8599999,
        1.8599999,  2.86     ], dtype=float32)>

In [91]:
tf.sin(k)

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([-0.00159255, -0.8423304 , -0.90863353, -0.13954322,  0.7578425 ,
        0.9584713 ,  0.27788603], dtype=float32)>

In [92]:
tf.cos(k)

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([-0.99999875, -0.5389615 ,  0.4175944 ,  0.99021596,  0.65243757,
       -0.28518897, -0.960614  ], dtype=float32)>

## Функции активации и функции потерь, используемые в нейронных сетях